color= input('enter a color: ')
plural_noun=input('enter a plural noun: ')
celebrity=input('enter a celebrity: ')
print('the roses are '+color)
print(plural_noun+' are blue')
print('I love', celebrity)
